<a href="https://colab.research.google.com/github/polinakochneva1/me_labs_house/blob/main/firstlab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 1

##Загрузка датасета
В файле classification datasets расположены ссылки на датасеты. Выберите один в соответствии со своим вариантом, скачайте и прочитайте файл

**Не забудьте загрузить нужные библиотеки**

Например: pip3 install pandas

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/global-data-on-sustainable-energy (1).csv")
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

##Первое знакомство с датасетом
В следующих ячейках выведите:


1.   Колонки датасета
2.   Первые 5 значений
3.   Последние 5 значений
4.   Статистику по числовым колонкам

In [4]:
#Колонки
df.columns

Index(['Entity', 'Year', 'Access to electricity (% of population)',
       'Access to clean fuels for cooking',
       'Renewable-electricity-generating-capacity-per-capita',
       'Financial flows to developing countries (US $)',
       'Renewable energy share in the total final energy consumption (%)',
       'Electricity from fossil fuels (TWh)', 'Electricity from nuclear (TWh)',
       'Electricity from renewables (TWh)',
       'Low-carbon electricity (% electricity)',
       'Primary energy consumption per capita (kWh/person)',
       'Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
       'Value_co2_emissions_kt_by_country',
       'Renewables (% equivalent primary energy)', 'gdp_growth',
       'gdp_per_capita', 'Density\n(P/Km2)', 'Land Area(Km2)', 'Latitude',
       'Longitude'],
      dtype='object')

In [5]:
#Первые 5 значений
df[:5]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953

In [6]:
#Последние 5 значений
df[-5:]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.6802,10.00,11020.00046,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.0115,9.51,10340.00015,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.9858,9.83,12380.00011,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.6553,10.47,11760.00023,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.1318,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [8]:
#Статистику
df.describe()

,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Land Area(Km2),Latitude,Longitude
count,3649.000000,3639.000000,3480.000000,2718.000000,1.560000e+03,3455.000000,3628.000000,3523.000000,3628.000000,3607.000000,3649.000000,3442.000000,3.221000e+03,1512.000000,3332.000000,3367.000000,3.648000e+03,3648.000000,3648.000000
mean,2010.038367,78.933702,63.255287,113.137498,9.422400e+07,32.638165,70.365003,13.450190,23.968010,36.801182,25743.981745,5.307345,1.598665e+05,11.986707,3.441610,13283.774348,6.332135e+05,18.246388,14.822695
std,6.054228,30.275541,39.043658,244.167256,2.981544e+08,29.894901,348.051866,73.006623,104.431085,34.314884,34773.221366,3.532020,7.736611e+05,14.994644,5.686720,19709.866716,1.585519e+06,24.159232,66.348148
min,2000.000000,1.252269,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.110000,1.000000e+01,0.000000,-62.075920,111.927225,2.100000e+01,-40.900557,-175.198242
25%,2005.000000,59.800890,23.175000,3.540000,2.600000e+05,6.515000,0.290000,0.000000,0.040000,2.877847,3116.737300,3.170000,2.020000e+03,2.137095,1.383302,1337.813437,2.571300e+04,3.202778,-11.779889
50%,2010.000000,98.361570,83.150000,32.910000,5.665000e+06,23.300000,2.970000,0.000000,1.470000,27.865068,13120.570000,4.300000,1.050000e+04,6.290766,3.559855,4578.633208,1.176000e+05,17.189877,19.145136
75%,2015.000000,100.000000,100.000000,112.210000,5.534750e+07,55.245000,26.837500,0.000000,9.600000,64.403792,33892.780000,6.027500,6.058000e+04,16.841638,5.830099,15768.615365,5.131200e+05,38.969719,46.199616
max,2020.000000,100.000000,100.000000,3060.190000,5.202310e+09,96.040000,5184.130000,809.410000,2184.940000,100.000010,262585.700000,32.570000,1.070722e+07,86.836586,123.139555,123514.196700,9.984670e+06,64.963051,178.065032

**Ответьте на следующие вопросы:**


1.   Какие средние значения в каждой числовой колонке вашего датасета?
2.   Минимальные и максимальные значения в каждой числовой колонке вашего датасета



1.   **Ответ 1.**
2.   **Ответ 2.**

##Типизация
Присвойте соответствующим колонкам один из типов (category, float, int)

In [13]:
df['Year'] = df['Year'].astype(int)
df['Electricity from fossil fuels (TWh)'] = df['Electricity from fossil fuels (TWh)'].astype(float)
df['Entity'] = df['Entity'].astype('category')
df.info()

#Вывести типы колонок тут

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3649 non-null   category
 1   Year                                                              3649 non-null   int64
 2   Access to electricity (% of population)                           3639 non-null   float64
 3   Access to clean fuels for cooking                                 3480 non-null   float64
 4   Renewable-electricity-generating-capacity-per-capita              2718 non-null   float64
 5   Financial flows to developing countries (US $)                    1560 non-null   float64
 6   Renewable energy share in the total final energy consumption (%)  3455 non-null   float64
 7   Electricity from fossil fuels (TWh)                               3628 non-null   float64
 8   Electricity from nuclear (TWh)                                    3523 non-null   float64
 9   Electricity from renewables (TWh)                                 3628 non-null   float64
 10  Low-carbon electricity (% electricity)                            3607 non-null   float64
 11  Primary energy consumption per capita (kWh/person)                3649 non-null   float64
 12  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   float64
 13  Value_co2_emissions_kt_by_country                                 3221 non-null   float64
 14  Renewables (% equivalent primary energy)                          1512 non-null   float64
 15  gdp_growth                                                        3332 non-null   float64
 16  gdp_per_capita                                                    3367 non-null   float64
 17  Density\n(P/Km2)                                                  3648 non-null   object
 18  Land Area(Km2)                                                    3648 non-null   float64
 19  Latitude                                                          3648 non-null   float64
 20  Longitude                                                         3648 non-null   float64
dtypes: category(1), float64(18), int64(1), object(1)
memory usage: 582.9+ KB

Какие признаки вы можете выделить в своем датасете (категориальные, числовые и др., **минимум 3 разных**, помните что можно также выделить признаки более точно, например числовые - порядковые, количественные и т.д.)?

##Фильтрация
Офильтруйте 3 колонки вашего датасета и выведите результат

In [15]:
#Фильтр колонки 1
df.loc[df['Year'] > 2017 ]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
18,Afghanistan,2018,96.616135,30.9,9.55,70100000.0,17.96,0.20,0.0,0.97,...,924.25085,2.44,6070.000172,NaN,1.189228,485.668419,60,652230.0,33.939110,67.709953
19,Afghanistan,2019,97.700000,31.9,9.58,4620000.0,18.51,0.18,0.0,0.89,...,802.61255,2.41,6079.999924,NaN,3.911603,494.179350,60,652230.0,33.939110,67.709953
20,Afghanistan,2020,97.700000,33.2,9.35,NaN,NaN,0.12,0.0,0.68,...,702.88800,NaN,NaN,NaN,-2.351101,516.747871,60,652230.0,33.939110,67.709953
39,Albania,2018,100.000000,79.8,NaN,NaN,NaN,0.00,0.0,8.47,...,14609.70100,2.57,5110.000134,NaN,4.019360,5287.663694,105,28748.0,41.153332,20.168331
40,Albania,2019,100.000000,80.7,NaN,NaN,NaN,0.00,0.0,5.17,...,11585.55500,2.50,4829.999924,NaN,2.113420,5395.659532,105,28748.0,41.153332,20.168331
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3626,Zambia,2019,43.000000,11.2,142.11,78570000.0,84.50,2.05,0.0,12.62,...,2983.88160,7.09,6800.000191,NaN,1.441306,1305.001031,25,752618.0,-13.133897,27.849332
3627,Zambia,2020,44.524475,10.4,138.23,NaN,NaN,2.00,0.0,13.10,...,3099.08300,NaN,NaN,NaN,-2.785055,985.132436,25,752618.0,-13.133897,27.849332
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [16]:
#Фильтр колонки 2
df.loc[df['Entity'] == 'Zimbabwe']

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
3628,Zimbabwe,2000,33.654890,33.50,61.42,40000.0,69.26,3.30,0.0,3.44,...,4919.5225,9.39,13700.000000,NaN,-3.059190,563.057504,38,390757.0,-19.015438,29.154857
3629,Zimbabwe,2001,34.172844,33.60,61.20,280000.0,71.53,4.33,0.0,3.25,...,4614.9575,9.23,13900.000000,NaN,1.439615,568.386290,38,390757.0,-19.015438,29.154857
3630,Zimbabwe,2002,34.200000,33.50,62.72,NaN,74.30,4.12,0.0,4.14,...,4561.2430,9.96,12489.999770,NaN,-8.894024,530.530446,38,390757.0,-19.015438,29.154857
3631,Zimbabwe,2003,35.188350,32.80,62.58,10000.0,77.83,2.98,0.0,5.56,...,4397.3420,11.47,10180.000310,NaN,-16.995075,478.007604,38,390757.0,-19.015438,29.154857
3632,Zimbabwe,2004,35.690600,32.20,62.38,NaN,81.58,3.63,0.0,5.78,...,4045.2322,11.90,9770.000458,NaN,-5.807538,482.998451,38,390757.0,-19.015438,29.154857
3633,Zimbabwe,2005,36.192314,31.70,62.09,500000.0,80.15,3.84,0.0,5.20,...,4160.4126,13.24,10510.000230,NaN,-5.711084,476.555403,38,390757.0,-19.015438,29.154857
3634,Zimbabwe,2006,37.200000,31.40,61.68,NaN,78.59,2.23,0.0,5.45,...,4158.7817,14.09,9829.999924,NaN,-3.461495,447.854740,38,390757.0,-19.015438,29.154857
3635,Zimbabwe,2007,37.204010,31.00,61.18,NaN,77.97,1.86,0.0,5.49,...,4036.7202,14.40,9760.000229,NaN,-3.653327,431.787259,38,390757.0,-19.015438,29.154857
3636,Zimbabwe,2008,37.719345,30.50,67.35,NaN,81.86,1.60,0.0,5.79,...,3324.8596,16.34,7599.999905,NaN,-17.668946,356.693234,38,390757.0,-19.015438,29.154857
3637,Zimbabwe,2009,43.369083,30.50,66.60,20000.0,82.09,1.57,0.0,5.54,...,3254.2820,15.00,7750.000000,NaN,12.019560,771.599032,38,390757.0,-19.015438,29.154857
3638,Zimbabwe,2010,38.782550,30.15,65.79,NaN,82.27,2.49,0.0,5.95,...,3592.6724,12.71,9600.000381,NaN,19.675323,948.331481,38,390757.0,-19.015438,29.154857
3639,Zimbabwe,2011,36.900000,30.10,66.20,1080000.0,79.27,3.43,0.0,5.51,...,3860.7898,11.77,11409.999850,NaN,14.193913,1093.653409,38,390757.0,-19.015438,29.154857
3640,Zimbabwe,2012,44.000000,29.80,65.14,NaN,77.50,3.25,0.0,5.68,...,4106.9497,10.42,12010.000230,NaN,16.665429,1304.968011,38,390757.0,-19.015438,29.154857
3641,Zimbabwe,2013,40.498375,29.80,64.44,319000000.0,78.87,3.90,0.0,5.36,...,4085.3320,10.48,12279.999730,NaN,1.989493,1429.998461,38,390757.0,-19.015438,29.154857
3642,Zimbabwe,2014,32.300000,29.50,63.38,17830000.0,80.27,3.92,0.0,5.79,...,3940.8862,10.40,12079.999920,NaN,2.376929,1434.896277,38,390757.0,-19.015438,29.154857
3643,Zimbabwe,2015,33.700000,29.50,63.54,NaN,80.82,4.02,0.0,5.37,...,3860.9202,10.36,12430.000310,NaN,1.779873,1445.069702,38,390757.0,-19.015438,29.154857
3644,Zimbabwe,2016,42.561730,29.80,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.6802,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.80,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.0115,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.90,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.9858,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.10,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.6553,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.40,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.1318,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [17]:
#Фильтр колонки 3
df.loc[df['Renewable-electricity-generating-capacity-per-capita'] < 70]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3641,Zimbabwe,2013,40.498375,29.8,64.44,319000000.0,78.87,3.90,0.0,5.36,...,4085.33200,10.48,12279.999730,NaN,1.989493,1429.998461,38,390757.0,-19.015438,29.154857
3642,Zimbabwe,2014,32.300000,29.5,63.38,17830000.0,80.27,3.92,0.0,5.79,...,3940.88620,10.40,12079.999920,NaN,2.376929,1434.896277,38,390757.0,-19.015438,29.154857
3643,Zimbabwe,2015,33.700000,29.5,63.54,NaN,80.82,4.02,0.0,5.37,...,3860.92020,10.36,12430.000310,NaN,1.779873,1445.069702,38,390757.0,-19.015438,29.154857
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857

##Группировка
Сгруппируйте датасет по какому-либо категориальному признаку и выведите среднее значение численных колонок (см. метод mean в pandas)

In [18]:
#Группировка
df.groupby('Entity'	).mean()

<ipython-input-18-8472c0d58030>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Entity'	).mean()

,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Land Area(Km2),Latitude,Longitude
Entity,,,,,,,,,,,,,,,,,,,
Afghanistan,2010.0,52.520488,19.802381,8.581429,3.296947e+07,25.6805,0.189524,0.0,0.740952,78.872636,697.268136,2.039000,4073.000025,NaN,6.163893,439.055765,652230.0,33.939110,67.709953
Albania,2010.0,99.981429,63.592857,NaN,NaN,NaN,0.048571,0.0,5.184286,98.855430,11353.520929,3.177500,4303.000004,NaN,3.859305,3623.224775,28748.0,41.153332,20.168331
Algeria,2010.0,99.108146,98.904762,9.390000,5.056250e+05,0.2870,46.895714,0.0,0.365238,0.742125,12925.532952,4.498500,119921.000066,0.185239,2.885714,3787.817377,2381741.0,28.033886,1.659626
Angola,2010.0,35.138564,44.933333,43.951429,9.525000e+06,57.6970,2.040476,0.0,4.420952,68.980548,3102.008457,2.896500,21689.499863,NaN,4.945895,2982.568601,1246700.0,-11.202692,17.873887
Antigua and Barbuda,2010.0,98.823761,100.000000,22.455238,9.700000e+06,0.2005,0.271429,0.0,0.002857,0.861557,32065.486190,3.624000,512.999998,NaN,1.515946,13555.401528,443.0,17.060816,-61.796428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uzbekistan,2010.0,99.848840,84.976190,61.972381,5.868556e+07,1.2385,43.476667,0.0,6.438095,12.974661,19346.599286,15.948500,118427.000704,3.192610,6.253772,1438.250604,447400.0,41.377491,64.585262
Vanuatu,2010.0,41.269784,12.050000,19.339524,5.694000e+06,43.6560,0.046667,0.0,0.008095,11.904762,2471.556643,3.516500,122.999999,NaN,2.441195,2458.898510,12189.0,-15.376706,166.959158
Yemen,2010.0,60.928522,59.290476,1.672381,1.059562e+07,1.3115,4.907619,0.0,0.091905,2.593720,2998.960281,3.067611,NaN,NaN,NaN,NaN,527968.0,15.552727,48.516388
Zambia,2010.0,27.753585,14.471429,146.577619,1.881594e+08,86.8955,0.492381,0.0,10.701429,96.479406,3027.719648,9.181500,3559.000016,NaN,5.442444,1144.799404,752618.0,-13.133897,27.849332
Zimbabwe,2010.0,39.172120,30.930952,66.068571,2.651154e+07,79.1500,3.229048,0.0,5.007143,60.849178,3825.827057,11.474762,11040.000110,NaN,0.132669,916.669430,390757.0,-19.015438,29.154857

##Задание для гениев *
Агрегируйте числовой признак по категориальному признаку с использованием метода **без использования** библиотеки pandas, и вычислите медиану и среднее значение для каждой категории.

In [ ]:
#Агрегация