<a href="https://colab.research.google.com/github/polinakochneva1/me_labs_house/blob/main/lab3/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 3

##Обработка пропущенных значений

Обработайте пропущенные значения:


* Удалите пропущенные значения
* Заполните при помощи медианы, среднего для числовых значений
* Заполните при помощи моды для категориальных значений
* Интерполируйте
Выведите статистку после каждого метода и объясните

In [3]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)

In [5]:
import pandas as pd

df = pd.read_csv('/content/global-data-on-sustainable-energy.csv')
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [7]:
#Удаление
df_cleaned = df.dropna()
df_cleaned

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
43,Algeria,2001,98.96687,97.30,8.79,810000.0,0.43,24.96,0.0,0.07,...,9961.640,4.07,78650.00000,0.065218,3.000000,1740.606654,18,2381741.0,28.033886,1.659626
44,Algeria,2002,98.95306,97.80,8.68,310000.0,0.51,25.94,0.0,0.06,...,10180.350,4.12,82400.00153,0.051677,5.600000,1781.828908,18,2381741.0,28.033886,1.659626
45,Algeria,2003,98.93401,98.00,8.57,90000.0,0.47,27.54,0.0,0.26,...,10510.461,4.08,88190.00244,0.228104,7.200000,2103.381291,18,2381741.0,28.033886,1.659626
46,Algeria,2004,98.91208,98.20,8.46,140000.0,0.44,29.14,0.0,0.25,...,10759.022,3.96,89489.99786,0.206787,4.300000,2610.185422,18,2381741.0,28.033886,1.659626
47,Algeria,2005,98.88961,98.50,8.34,160000.0,0.58,31.36,0.0,0.55,...,11113.723,3.90,94190.00244,0.434119,5.900000,3113.094883,18,2381741.0,28.033886,1.659626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3559,Uzbekistan,2015,100.00000,85.35,60.83,270000.0,1.71,47.55,0.0,7.00,...,17386.195,7.86,99169.99817,3.012993,7.218774,2753.971072,79,447400.0,41.377491,64.585262
3560,Uzbekistan,2016,100.00000,85.20,59.88,690000.0,1.61,48.75,0.0,7.25,...,16374.342,7.82,105230.00340,3.567936,5.932151,2704.677188,79,447400.0,41.377491,64.585262
3561,Uzbekistan,2017,100.00000,84.90,58.24,60130000.0,1.75,49.71,0.0,8.35,...,16642.676,7.88,109529.99880,3.972285,4.395275,1916.764642,79,447400.0,41.377491,64.585262
3562,Uzbekistan,2018,100.00000,84.30,59.09,84130000.0,1.49,53.58,0.0,5.85,...,16445.740,9.05,112470.00120,2.927033,5.354997,1597.068337,79,447400.0,41.377491,64.585262
3563,Uzbekistan,2019,100.00000,84.60,57.96,65940000.0,1.57,53.64,0.0,6.47,...,16212.221,8.37,116709.99910,3.197033,5.709632,1784.009816,79,447400.0,41.377491,64.585262

**Мы удалили все строки, которые содержали в одном из столбце значение NaN. Если посмотреть на первую таблицу, можно увидить данное значение в 4 строке, в колонке Financial flows to developing countries (US $), следовательно мы удалили эту строку.**

In [8]:
#Заполнение при помощи среднего
df_filled_mean = df.fillna(df.mean())

df_filled_mean

<ipython-input-8-20526bfdd642>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_filled_mean = df.fillna(df.mean())

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,11.986707,3.441610,13283.774348,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,11.986707,3.441610,13283.774348,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,11.986707,3.441610,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,11.986707,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,94224000.0,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,11.986707,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,11.986707,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,11.986707,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,11.986707,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,11.986707,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,159866.462686,11.986707,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

**Тк у категориальных переменных нет среднего,
его надо или заменить с помощью моды, или преобразовать в числа. Мы заменили NaN средним значением**

In [9]:
#Заполнение при помощи медианы
df_filled_median = df.fillna(df.median())

df_filled_median

<ipython-input-9-1d6bd374d546>:2: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_filled_median = df.fillna(df.median())

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,6.290766,3.559855,4578.633208,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,6.290766,3.559855,4578.633208,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,6.290766,3.559855,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,6.290766,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,5665000.0,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,6.290766,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,6.290766,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,6.290766,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,6.290766,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,6.290766,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,10500.000000,6.290766,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

**Тк у категориальных переменных нет медианы,
её надо или заменить с помощью моды, или преобразовать в числа. Если обратиться к первой таблицы, можно так же увидить разницу в 4 строке, мы заменили значение NaN медианой**

In [10]:
#Заполнение при помощи моды
df_filled_mode = df.fillna(df["Year"].mode()[0])

df_filled_mode

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,2013.0,2013.000000,2013.000000,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,2013.0,2013.000000,2013.000000,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,2013.0,2013.000000,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,2013.0,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,2013.0,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,2013.0,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,2013.0,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,2013.0,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,2013.0,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,2013.0,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,2013.000000,2013.0,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

**Мы заполнили столбец Year при помощи моды. Она возвращает объект Series, так как значений моды может быть несколько**

In [11]:
#Заполнение при помощи интерполяции
df_interpolated = df.interpolate()

df_interpolated

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,17900000.0,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,2.523421,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,2.523421,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,2.523421,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,2.523421,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,11760.000230,2.523421,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

**Надо преобразовывать, тк интерполяция не работает для категориальных значений.Применяем линейную интерполяцию для заполнения пропущенных значений**

**Объясните**

**Все объяснения предоставлены под каждой из таблиц**

##Поиск выбросов и аномалий

**Те, кто выполняет задания со * делают поиск выбросов с помощью написанного ранее класса**

Найти выбросы по числовой переменной (использовать метод основанный на среднем и на межквартильном размахе). Объясните результат

Вывести статистику с выбросами и без. Сравните и объясните результат

In [ ]:
#Методом среднего

In [ ]:
#При помощи межквартильного размаха

In [ ]:
#Статистика и объяснение

**Объяснения**

##Дубликаты

Проверьте датафрейм на дубликаты и удалите их, если дублей нет - создайте.

In [16]:
#Проверка на дубли
df_duplicated = df[df.duplicated()]
df_duplicated

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Antigua and Barbuda,2012,100.000000,100.0,3.32,NaN,0.15,0.31,0.0,0.00,...,33159.37000,4.08,699.999988,NaN,3.372866,13272.734940,223,443.0,17.060816,-61.796428
97,Antigua and Barbuda,2013,100.000000,100.0,4.37,2580000.0,0.15,0.31,0.0,0.00,...,32853.87500,4.13,469.999999,NaN,-0.600876,12910.590630,223,443.0,17.060816,-61.796428
98,Antigua and Barbuda,2014,100.000000,100.0,4.32,NaN,0.14,0.32,0.0,0.00,...,33313.00000,4.01,479.999989,NaN,3.795728,13501.580920,223,443.0,17.060816,-61.796428
99,Antigua and Barbuda,2015,100.000000,100.0,36.34,6970000.0,0.48,0.32,0.0,0.01,...,33830.76000,3.98,490.000009,NaN,3.825293,14285.329780,223,443.0,17.060816,-61.796428
100,Antigua and Barbuda,2016,100.000000,100.0,37.03,NaN,0.60,0.32,0.0,0.00,...,34089.41000,3.85,500.000000,NaN,5.496459,15198.742970,223,443.0,17.060816,-61.796428

**Дубликаты найдены в 101 строке**

In [18]:
#Удаление дублей
df = df.drop_duplicates()
df_no_duplicates = df[df.duplicated()]
df_no_duplicates

Empty DataFrame
Columns: [Entity, Year, Access to electricity (% of population), Access to clean fuels for cooking, Renewable-electricity-generating-capacity-per-capita, Financial flows to developing countries (US $), Renewable energy share in the total final energy consumption (%), Electricity from fossil fuels (TWh), Electricity from nuclear (TWh), Electricity from renewables (TWh), Low-carbon electricity (% electricity), Primary energy consumption per capita (kWh/person), Energy intensity level of primary energy (MJ/$2017 PPP GDP), Value_co2_emissions_kt_by_country, Renewables (% equivalent primary energy), gdp_growth, gdp_per_capita, Density\n(P/Km2), Land Area(Km2), Latitude, Longitude]
Index: []

[0 rows x 21 columns]

**Мы удалили все дубликаты**

## Преобразование признаков

Масштабируйте числовые признаки через MinMaxScaler, StandardScaler

In [40]:
# Получаем числовые признаки
num_features = df.select_dtypes(include=['float64']).columns
num_features

Index(['Access to electricity (% of population)',
       'Access to clean fuels for cooking',
       'Renewable-electricity-generating-capacity-per-capita',
       'Financial flows to developing countries (US $)',
       'Renewable energy share in the total final energy consumption (%)',
       'Electricity from fossil fuels (TWh)', 'Electricity from nuclear (TWh)',
       'Electricity from renewables (TWh)',
       'Low-carbon electricity (% electricity)',
       'Primary energy consumption per capita (kWh/person)',
       'Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
       'Value_co2_emissions_kt_by_country',
       'Renewables (% equivalent primary energy)', 'gdp_growth',
       'gdp_per_capita', 'Land Area(Km2)', 'Latitude', 'Longitude'],
      dtype='object')

In [39]:
# Выбираем индекс и выводим первичные уникальные значения в числовом призанке
df.Longitude.unique()

array([  67.709953  ,   20.168331  ,    1.659626  ,   17.873887  ,
        -61.796428  ,  -63.616672  ,   45.038189  ,  -69.96833   ,
        133.775136  ,   14.550072  ,   47.576927  ,  -78.035889  ,
         50.5577    ,   90.356331  ,  -59.543198  ,   27.953389  ,
          4.469936  ,  -88.49765   ,    2.315834  ,  -64.790337  ,
         90.433601  ,   17.679076  ,   24.684866  ,  -51.92528   ,
         25.48583   ,   -1.561593  ,   29.918886  ,  104.990963  ,
         12.354722  , -106.346771  ,   81.2524    ,   20.939444  ,
         18.732207  ,  -71.542969  ,  104.195397  ,  -74.297333  ,
         43.3333    ,   13.7289    ,  -83.753428  ,   15.2       ,
        -77.781167  ,   33.429859  ,   15.472962  ,    9.501785  ,
         42.590275  ,  -61.370976  ,  -70.162651  ,  -78.183406  ,
         30.802498  ,  -88.89653   ,   10.267895  ,   39.782334  ,
         25.013607  ,   31.465866  ,   40.489673  ,  178.065032  ,
         25.748151  ,    2.213749  ,           nan,   11.609444  ,
        -16.56666666,   43.356892  ,   10.451526  ,   -1.023194  ,
         21.824312  ,  -61.679     ,  -90.230759  ,   -9.696645  ,
        -15.180413  ,  -58.93018   ,  -72.285215  ,  -86.241905  ,
         19.503304  ,  -19.020835  ,   78.96288   ,  113.921327  ,
         43.679291  ,   -8.24389   ,   34.851612  ,   12.56738   ,
        -77.297508  ,  138.252924  ,   36.238414  ,   66.923684  ,
         37.906193  , -157.3768317 ,   47.481766  ,   74.766098  ,
         24.603189  ,   35.862285  ,   28.233608  ,   -9.429499  ,
         17.228331  ,   23.881275  ,    6.129583  ,   46.869107  ,
         34.301525  ,  101.975766  ,   73.22068   ,   -3.996166  ,
         14.375416  ,  -10.940835  ,   57.552152  , -102.552784  ,
        103.846656  ,   19.37439   ,   -7.09262   ,   35.529562  ,
         95.955974  ,   18.49041   ,  166.931503  ,   84.124008  ,
          5.291266  ,  165.618042  ,  174.885971  ,  -85.207229  ,
          8.081666  ,    8.675277  ,   21.745275  ,    8.468946  ,
         55.975413  ,   69.345116  ,  -80.782127  ,  143.95555   ,
        -58.443832  ,  -75.015152  ,  121.774017  ,   19.145136  ,
         -8.224454  ,  -66.5       ,   51.183884  ,   24.96676   ,
         29.873888  ,  -62.782998  ,  -60.978893  ,  -61.287228  ,
       -172.104629  ,    6.733343  ,   45.079162  ,  -14.452362  ,
         21.005859  ,   55.491977  ,  -11.779889  ,  103.819836  ,
         19.699024  ,   14.995463  ,  160.156194  ,   46.199616  ,
         22.937506  ,   31.3069788 ,   -3.74922   ,   80.771797  ,
         30.217636  ,  -56.027783  ,   18.643501  ,    8.227512  ,
         71.276093  ,  100.992541  ,    0.824782  , -175.198242  ,
        -61.222503  ,    9.537499  ,   35.243322  ,   59.556278  ,
        177.64933   ,   32.290275  ,   31.16558   ,   53.847818  ,
         -3.435973  ,  -95.712891  ,  -55.765835  ,   64.585262  ,
        166.959158  ,   48.516388  ,   27.849332  ,   29.154857  ])

In [37]:
from sklearn.preprocessing import MinMaxScaler
# MinMax масштабирование
scaler_minmax = MinMaxScaler()
df_minmax_scaled = df.copy()
df_minmax_scaled[num_features] = scaler_minmax.fit_transform(df[num_features])
df_minmax_scaled.Longitude.unique()

array([0.68761236, 0.55303392, 0.5006404 , 0.54653892, 0.32101218,
       0.31585953, 0.62343427, 0.29787957, 0.87462638, 0.53713003,
       0.6306208 , 0.27504233, 0.63905862, 0.7517186 , 0.32739051,
       0.57507147, 0.50859569, 0.2454277 , 0.50249796, 0.31253717,
       0.75193733, 0.54598746, 0.5658191 , 0.34895493, 0.56808643,
       0.49152194, 0.5806353 , 0.79314558, 0.53091555, 0.1949013 ,
       0.72594765, 0.55521675, 0.54896861, 0.29342216, 0.79089353,
       0.28562524, 0.61860815, 0.5348055 , 0.2588574 , 0.53896982,
       0.27576338, 0.59057399, 0.5397425 , 0.52283959, 0.61650484,
       0.32221653, 0.2973295 , 0.27462474, 0.58313659, 0.24429857,
       0.52500826, 0.60855626, 0.56674968, 0.58501442, 0.61055856,
       1.        , 0.56882899, 0.50220899,        nan, 0.52880585,
       0.44904633, 0.61867494, 0.52552807, 0.49304601, 0.55772159,
       0.32134459, 0.2405217 , 0.46849364, 0.45297046, 0.32912581,
       0.29132105, 0.25181315, 0.55115139, 0.44209919, 0.71946659,
       0.81842521, 0.61958757, 0.47260603, 0.59459862, 0.53151753,
       0.2771325 , 0.88730188, 0.59852431, 0.68538663, 0.60324537,
       0.05044796, 0.63035142, 0.70758655, 0.56558789, 0.59745958,
       0.5758647 , 0.46924986, 0.54471151, 0.56354434, 0.51329373,
       0.62861714, 0.59304146, 0.78461031, 0.70321185, 0.48463027,
       0.53663563, 0.46497165, 0.65885817, 0.20564113, 0.78990633,
       0.55078647, 0.47586498, 0.59651772, 0.76756979, 0.54828414,
       0.96848376, 0.73407645, 0.51092067, 0.96476568, 0.99100087,
       0.25474206, 0.51881959, 0.52049996, 0.55749785, 0.51991589,
       0.65439482, 0.6922411 , 0.26726841, 0.90344459, 0.33050254,
       0.28359328, 0.84065421, 0.55013751, 0.47266104, 0.30769754,
       0.64083119, 0.56661707, 0.58050792, 0.31821945, 0.32332642,
       0.3224536 , 0.00875724, 0.51500283, 0.62355025, 0.45503139,
       0.55540475, 0.65302633, 0.4625965 , 0.78983041, 0.55170543,
       0.53839082, 0.94930456, 0.62672198, 0.56087276, 0.58456465,
       0.48532931, 0.72458718, 0.58148099, 0.33734177, 0.54871751,
       0.51923245, 0.69770721, 0.78182705, 0.49827717, 0.        ,
       0.32263682, 0.52294069, 0.59570745, 0.66453135, 0.99882325,
       0.58734811, 0.58416438, 0.64837213, 0.48621604, 0.22500315,
       0.33808328, 0.67876715, 0.96856205, 0.63328018, 0.57477691,
       0.57847253])

In [41]:
from sklearn.preprocessing import StandardScaler
# Standard масштабирование
scaler_std = StandardScaler()
df_std_scaled = df.copy()
df_std_scaled[num_features] = scaler_std.fit_transform(df[num_features])
df_std_scaled.Longitude.unique()

array([ 7.97226607e-01,  8.05805356e-02, -1.98421109e-01,  4.59939101e-02,
       -1.15496255e+00, -1.18240105e+00,  4.55470690e-01, -1.27814643e+00,
        1.79309826e+00, -4.10953319e-03,  4.93739822e-01, -1.39975744e+00,
        5.38672224e-01,  1.13859985e+00, -1.12099719e+00,  1.97933099e-01,
       -1.56058279e-01, -1.55745883e+00, -1.88529379e-01, -1.20009297e+00,
        1.13976463e+00,  4.30573140e-02,  1.48663132e-01, -1.00616411e+00,
        1.60736925e-01, -2.46978012e-01,  2.27561153e-01,  1.35920342e+00,
       -3.72024081e-02, -1.82651785e+00,  1.00136650e+00,  9.22043523e-02,
        5.89322918e-02, -1.30188266e+00,  1.34721100e+00, -1.34340216e+00,
        4.29771062e-01, -1.64879432e-02, -1.48594406e+00,  5.68753153e-03,
       -1.39591774e+00,  2.80485830e-01,  9.80218173e-03, -8.02078002e-02,
        4.18570646e-01, -1.14854926e+00, -1.28107564e+00, -1.40198112e+00,
        2.40880788e-01, -1.56347158e+00, -6.86593990e-02,  3.76243527e-01,
        1.53618599e-01,  2.50880448e-01,  3.86906010e-01,  2.46072757e+00,
        1.64691172e-01, -1.90068216e-01,             nan, -4.84367861e-02,
       -4.73165648e-01,  4.30126690e-01, -6.58913312e-02, -2.38862144e-01,
        1.05542921e-01, -1.15319243e+00, -1.58358385e+00, -3.69606412e-01,
       -4.52269153e-01, -1.11175651e+00, -1.31307134e+00, -1.52345556e+00,
        7.05558674e-02, -5.10159970e-01,  9.66854095e-01,  1.49382042e+00,
        4.34986557e-01, -3.47707472e-01,  3.01917444e-01, -3.39967851e-02,
       -1.38862703e+00,  1.86059678e+00,  3.22822204e-01,  7.85374327e-01,
        3.47962433e-01, -2.59574892e+00,  4.92305358e-01,  9.03591480e-01,
        1.47431927e-01,  3.17152407e-01,  2.02157142e-01, -3.65579433e-01,
        3.62627492e-02,  1.36549739e-01, -1.31040633e-01,  4.83070089e-01,
        2.93625390e-01,  1.31375211e+00,  8.80295730e-01, -2.83676953e-01,
       -6.74231119e-03, -3.88361428e-01,  6.44107132e-01, -1.76932700e+00,
        1.34195405e+00,  6.86126078e-02, -3.30353139e-01,  3.12136915e-01,
        1.22300930e+00,  5.52874252e-02,  2.29289989e+00,  1.04465334e+00,
       -1.43677488e-01,  2.27310068e+00,  2.41280615e+00, -1.50785877e+00,
       -1.01614783e-01, -9.26666454e-02,  1.04351511e-01, -9.57768948e-02,
        6.20339247e-01,  8.21875180e-01, -1.44115444e+00,  1.94655861e+00,
       -1.10442526e+00, -1.35422262e+00,  1.61219247e+00,  6.51568154e-02,
       -3.47414492e-01, -1.22586456e+00,  5.48111370e-01,  1.52912424e-01,
        2.26882849e-01, -1.16983419e+00, -1.14263897e+00, -1.14728683e+00,
       -2.81775687e+00, -1.21939508e-01,  4.56088320e-01, -4.41294457e-01,
        9.32054972e-02,  6.13051895e-01, -4.01009393e-01,  1.34154976e+00,
        7.35061657e-02,  2.60432504e-03,  2.19076836e+00,  4.72978130e-01,
        1.22323293e-01,  2.48485370e-01, -2.79954470e-01,  9.94121849e-01,
        2.32064533e-01, -1.06800555e+00,  5.75951308e-02, -9.94162895e-02,
        8.50982875e-01,  1.29893090e+00, -2.11005612e-01, -2.86439023e+00,
       -1.14631116e+00, -7.96694446e-02,  3.07822111e-01,  6.74317482e-01,
        2.45446124e+00,  2.63307653e-01,  2.46353914e-01,  5.88267716e-01,
       -2.75232561e-01, -1.66622193e+00, -1.06405693e+00,  7.50124774e-01,
        2.29331677e+00,  5.07901330e-01,  1.96364536e-01,  2.16044121e-01])

In [44]:
df_scaled = df.copy() # копируем df, чтобы по ссылке не изменять оригинальный
df_scaled[num_features] = df_std_scaled[num_features]
df_scaled

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,-2.554231,-1.461530,-0.425678,-0.316058,0.413235,-0.201736,-0.184259,-0.226573,...,-0.731738,-1.038465,-0.205686,NaN,NaN,NaN,60,0.011996,0.649643,0.797227
1,Afghanistan,2001,-2.472934,-1.435914,-0.427153,-0.315689,0.433643,-0.201937,-0.184259,-0.224753,...,-0.733627,-1.010148,-0.205725,NaN,NaN,NaN,60,0.011996,0.649643,0.797227
2,Afghanistan,2002,-2.296709,-1.410298,-0.428750,-0.302873,0.173695,-0.201822,-0.184259,-0.224179,...,-0.734376,-1.106424,-0.205337,NaN,NaN,-0.664961,60,0.011996,0.649643,0.797227
3,Afghanistan,2003,-2.120656,-1.376997,-0.430307,-0.228995,0.134552,-0.201305,-0.184259,-0.223508,...,-0.733826,-1.106424,-0.205091,NaN,0.948082,-0.664390,60,0.011996,0.649643,0.797227
4,Afghanistan,2004,-1.944699,-1.341135,-0.431700,NaN,0.388144,-0.201248,-0.184259,-0.224179,...,-0.734567,-1.163057,-0.205337,NaN,-0.356585,-0.663340,60,0.011996,0.649643,0.797227
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,-1.201530,-0.856992,-0.205870,-0.316025,1.648073,-0.192139,-0.184259,-0.197746,...,-0.647607,1.328797,-0.192422,NaN,-0.472354,-0.599747,38,-0.152940,-1.542555,0.216044
3645,Zimbabwe,2017,-1.148116,-0.856992,-0.208123,-0.297438,1.666808,-0.193432,-0.184259,-0.188361,...,-0.652200,1.190046,-0.193301,NaN,0.222988,-0.611388,38,-0.152940,-1.542555,0.216044
3646,Zimbabwe,2018,-1.102066,-0.854430,-0.125378,-0.316092,1.592202,-0.191478,-0.184259,-0.177251,...,-0.641443,1.280659,-0.190664,NaN,0.243164,-0.610401,38,-0.152940,-1.542555,0.216044
3647,Zimbabwe,2019,-1.062133,-0.849307,-0.130007,-0.315287,1.634690,-0.191679,-0.184259,-0.185679,...,-0.654051,1.461884,-0.191466,NaN,-1.685908,-0.607250,38,-0.152940,-1.542555,0.216044
3648,Zimbabwe,2020,-0.865043,-0.841622,-0.133243,-0.316025,1.648073,-0.192426,-0.184259,-0.189414,...,-0.663356,1.328797,NaN,NaN,-1.704289,-0.612437,38,-0.152940,-1.542555,0.216044

Масштабируйте категориальные признаки через OneHotEncoder

In [59]:
# Объявим категориальные признаки
df = df.astype({'Access to electricity (% of population)': 'category',
                'Access to clean fuels for cooking': 'category',
                'Renewable-electricity-generating-capacity-per-capita': 'category',
                'Financial flows to developing countries (US $)': 'category',
                'Renewable energy share in the total final energy consumption (%)': 'category',
                'Electricity from fossil fuels (TWh)': 'category',
                'Electricity from nuclear (TWh)': 'category',
                'Electricity from renewables (TWh)': 'category',
                'Low-carbon electricity (% electricity)': 'category',
                'Primary energy consumption per capita (kWh/person)': 'category',
                'Energy intensity level of primary energy (MJ/$2017 PPP GDP)': 'category',
                'Value_co2_emissions_kt_by_country': 'category',
                'Renewables (% equivalent primary energy)': 'category',
                'gdp_growth': 'category',
                'gdp_per_capita': 'category',
                'Land Area(Km2)': 'category',
                'Latitude': 'category',
                'Longitude': 'category' })
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3649 entries, 0 to 3648
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3649 non-null   object
 1   Year                                                              3649 non-null   int64
 2   Access to electricity (% of population)                           3639 non-null   category
 3   Access to clean fuels for cooking                                 3480 non-null   category
 4   Renewable-electricity-generating-capacity-per-capita              2718 non-null   category
 5   Financial flows to developing countries (US $)                    1560 non-null   category
 6   Renewable energy share in the total final energy consumption (%)  3455 non-null   category
 7   Electricity from fossil fuels (TWh)                               3628 non-null   category
 8   Electricity from nuclear (TWh)                                    3523 non-null   category
 9   Electricity from renewables (TWh)                                 3628 non-null   category
 10  Low-carbon electricity (% electricity)                            3607 non-null   category
 11  Primary energy consumption per capita (kWh/person)                3649 non-null   category
 12  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   category
 13  Value_co2_emissions_kt_by_country                                 3221 non-null   category
 14  Renewables (% equivalent primary energy)                          1512 non-null   category
 15  gdp_growth                                                        3332 non-null   category
 16  gdp_per_capita                                                    3367 non-null   category
 17  Density\n(P/Km2)                                                  3648 non-null   object
 18  Land Area(Km2)                                                    3648 non-null   category
 19  Latitude                                                          3648 non-null   category
 20  Longitude                                                         3648 non-null   category
dtypes: category(18), int64(1), object(2)
memory usage: 1.4+ MB

In [60]:
cat_features = df.select_dtypes(include=['category']).columns
# Преобразование с использованием One-Hot Encoding
df_cat_encoded = pd.get_dummies(df, columns=cat_features, drop_first=True)

# Удаление исходных категориальных признаков
cat_features

Index(['Access to electricity (% of population)',
       'Access to clean fuels for cooking',
       'Renewable-electricity-generating-capacity-per-capita',
       'Financial flows to developing countries (US $)',
       'Renewable energy share in the total final energy consumption (%)',
       'Electricity from fossil fuels (TWh)', 'Electricity from nuclear (TWh)',
       'Electricity from renewables (TWh)',
       'Low-carbon electricity (% electricity)',
       'Primary energy consumption per capita (kWh/person)',
       'Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
       'Value_co2_emissions_kt_by_country',
       'Renewables (% equivalent primary energy)', 'gdp_growth',
       'gdp_per_capita', 'Land Area(Km2)', 'Latitude', 'Longitude'],
      dtype='object')

In [61]:
from sklearn.preprocessing import OneHotEncoder
# Применяем OneHotEncoder
encoder = OneHotEncoder(sparse=False, drop='first')
encoded_features = encoder.fit_transform(df[cat_features])

# Получаем имена новых признаков
encoded_columns = encoder.get_feature_names_out(cat_features)
encoded_columns

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

array(['Access to electricity (% of population)_1.2537057',
       'Access to electricity (% of population)_1.2792896',
       'Access to electricity (% of population)_1.613591', ...,
       'Longitude_177.64933', 'Longitude_178.065032', 'Longitude_nan'],
      dtype=object)

##Задание для гениев*


Реализовать расчет корреляции Спирмана

In [ ]:
#Функция по расчету тут

In [ ]:
#Пример использования тут и объяснение принципа работы

###Пример реализации

In [ ]:
import pandas as pd
import numpy as np


def corr_pearson(column_1, column_2):
  cov = np.cov(column_1, column_2)
  return cov/(column_1.std() * column_2.std())

In [ ]:
data = {
    'Рост': [170, 155, 180, 162, 175],
    'Вес': [65, 50, 75, 55, 70]
}
df = pd.DataFrame(data)
df

   Рост  Вес
0   170   65
1   155   50
2   180   75
3   162   55
4   175   70

In [ ]:
corr_pearson(df["Рост"], df["Вес"])

array([[0.96593129, 0.99674864],
       [0.99674864, 1.03527033]])